### Gets all the products (like the name implies!!)
# @name getAllProducts
GET localhost:3000/api/products/getAll

### Adds a new products, as the name says!
# @name addNewProduct
POST localhost:3000/api/products/addNew
Content-Type: application/json
Authorization: {{superSecretBearerToken}}

{

}

### Adds a new user, like the name says once again
# @name AddNewUser
POST localhost:3000/api/users/createNew
Content-Type: application/json

{
  "username": "Grög",
  "name": "Greg",
  "email": "greg@greg.com",
  "password": "123456"
}

### Try to log in
# @name logIn
POST localhost:3000/api/login
Content-Type: application/json

{
  "username": "Grög",
  "password": "123456"
}

### Adds an item to a certain users wishlist
# @name addToWishlist
POST localhost:3000/api/users/addToWishlist/{{userId}}/68dd1431471489c8f924fd01
Authorization: {{superSecretBearerToken}}

### Removes an item from the wishlist
# @name RemoveFromWishlist
POST localhost:3000/api/users/removeFromWishlist/{{userId}}/68dd1431471489c8f924fd01
Authorization: {{superSecretBearerToken}}

### Checkout testing
# @name checkout
POST localhost:3000/api/purchases/checkout/{{userId}}
Content-Type: application/json
Authorization: {{superSecretBearerToken}}

{
  "products": [
    {
      "id": "690e051dee2e7357665a61d3",
      "quantity": 4
    },
    {
      "id": "690e051dee2e7357665a61d0",
      "quantity": 6
    }
  ]
}

### get all users purchasehistory
# @name getHistory
GET localhost:3000/api/purchases/orders
Authorization: {{superSecretBearerToken}}

### Get orders from a specific user
# @name GetUserOrderHistory
GET localhost:3000/api/purchases/orders/690b13cebe4619050e62d457

### Test thing
# @name Test
GET localhost:3000/api/purchases/orders/test